"""
Response validation and summarization utilities.
This module provides functions to check if LLM responses are too long or contain markdown formatting,
and to summarize responses when needed.
"""

import logging
import re
from typing import Tuple

# Import configuration
from config.tunables import RESPONSE_SENTENCE_LIMIT

logger = logging.getLogger(__name__)


def count_sentences(text: str) -> int:
    """
    Count the number of sentences in a text string.
    
    Args:
        text: The text to analyze
        
    Returns:
        Number of sentences detected
    """
    # Remove extra whitespace and newlines
    text = text.strip()
    
    # Replace common abbreviations with placeholders to avoid false sentence breaks
    abbreviations = {
        'Dr.': 'Dr',
        'Mr.': 'Mr',
        'Ms.': 'Ms',
        'Mrs.': 'Mrs',
        'Prof.': 'Prof',
        'etc.': 'etc',
        'e.g.': 'eg',
        'i.e.': 'ie',
    }
    
    for abbr, replacement in abbreviations.items():
        text = text.replace(abbr, replacement)
    
    # Pattern to match sentence endings (. ! ?) followed by space or end of string
    sentence_pattern = r'[\.\!\?]+(?:\s+|$)'
    
    # Split by sentence endings
    sentences = re.split(sentence_pattern, text)
    
    # Filter out empty strings and count
    sentence_count = len([s for s in sentences if s.strip()])
    
    return sentence_count


def needs_summarization(response_text: str, sentence_limit: int = None) -> Tuple[bool, str]:
    """
    Check if a response needs summarization based on length.
    
    A response needs summarization when it exceeds the sentence limit.
    
    Args:
        response_text: The LLM-generated response to check
        sentence_limit: Maximum allowed sentences (defaults to RESPONSE_SENTENCE_LIMIT from config)
        
    Returns:
        Tuple of (needs_summarization: bool, reason: str)
    """
    # Use configured limit if not provided
    limit = sentence_limit if sentence_limit is not None else RESPONSE_SENTENCE_LIMIT
    
    # Check sentence count
    sentence_count = count_sentences(response_text)
    if sentence_count > limit:
        logger.info(f"Response exceeds sentence limit: {sentence_count} > {limit}")
        return True, f"response_too_long ({sentence_count} sentences)"
    
    return False, "ok"


def build_summarization_prompt(original_response: str, chat_history: list = None, persona: str = None) -> str:
    """
    Build a prompt for the LLM to summarize a response.
    
    Args:
        original_response: The original LLM response to summarize
        chat_history: Optional list of previous conversation turns
        persona: Optional persona description of the bot generating the response
        
    Returns:
        Formatted prompt for summarization
    """
    history_context = ""
    if chat_history:
        history_context = f"\nPrevious conversation context:\n{chat_history}\n"
    
    persona_context = ""
    if persona:
        persona_context = f"\nBOT PERSONA:\n{persona}\n"
    
    prompt = f"""You need to summarize a response generated by a virtual assistant to make it more concise while keeping all the essential information and adhering to the persona.

    PERSONA:
    {persona_context}

    CONTEXT:
    {history_context}

    ORIGINAL RESPONSE TO SUMMARIZE:
    {original_response}

REQUIREMENTS:
- Maintain all key information, advice, and questions asked within the original response
- Tone: Maintain the conversational tone and persona (if provided)
- Length: 1-7 sentences, max 350 characters (concise but complete) 
- Format: Maintain original formatting (lists, paragraphs)
- Citations: Use information naturally without saying "according to retrieved context"
"""
    return prompt


def summarize_response(llm_model, original_response: str, chat_history: list = None, persona: str = None) -> str:
    """
    Synchronously summarize a response using the LLM.
    
    Args:
        llm_model: The LLM model to use for summarization
        original_response: The original response to summarize
        chat_history: Optional conversation history for context
        persona: Optional persona description of the bot generating the response
        
    Returns:
        Summarized response text
    """
    try:
        prompt = build_summarization_prompt(original_response, chat_history, persona)
        
        # Use the LLM to generate summary
        response = llm_model.invoke(prompt)
        
        # Extract the text content
        if hasattr(response, 'content'):
            summary = response.content
        else:
            summary = str(response)
        
        logger.info(f"Successfully summarized response (original: {len(original_response)} chars, summary: {len(summary)} chars)")
        return summary.strip()
    
    except Exception as e:
        logger.error(f"Error during summarization: {e}", exc_info=True)
        # Return original response if summarization fails
        return original_response
