"""
Chatbot instruction sets (personas and prompts).
"""

from .personas import GENERAL_PERSONA, TEACHER_PERSONA, STUDY_ADVISER_PERSONA
from .prompts import (
    GENERAL_CHATBOT_SYSTEM_PROMPT,
    STUDY_ADVISER_SYSTEM_PROMPT,
    TEACHER_CHATBOT_SYSTEM_PROMPT,
    HANDOVER_MESSAGE,
)

__all__ = [
    "GENERAL_PERSONA",
    "TEACHER_PERSONA",
    "STUDY_ADVISER_PERSONA",
    "GENERAL_CHATBOT_SYSTEM_PROMPT",
    "STUDY_ADVISER_SYSTEM_PROMPT",
    "TEACHER_CHATBOT_SYSTEM_PROMPT",
    "HANDOVER_MESSAGE",
]
